#!/usr/bin/env python3
"""Tests for Job Opportunity Relationship Management"""

from pydantic import ValidationError
import pytest

from db.models import (
    CompanyCreate,
    CompanyRecord,
    CompanyUpdate,
    ProcessItemCreate,
    ProcessItemType,
)

from sample_data import opportunities

# TODO Move to pytest format and code coverage


def test_company_model():
    # Simulate a first creation request object
    company = CompanyCreate.model_validate({"name": "this is it", "url": "this too"})
    # Simulate a second update request object
    new_company_data = CompanyUpdate.model_validate({"name": "no more"})
    # Simulate a record after the creation request
    company_new = CompanyRecord.model_validate(company.model_dump(exclude_unset=True))
    # Update the simulated record with only the "patch" from the update request
    company_new.sqlmodel_update(new_company_data.model_dump(exclude_unset=True))
    assert company_new.id is not None  # This is autogenerated for records
    assert company_new.name == "no more"  # This was updated by the second request
    assert company_new.url == "this too"  # This should have passed through


if __name__ == "__main__":
    for i, opportunity in enumerate(opportunities):
        if i == 0:
            # Mocked 0 index is None
            continue
        print(f"#{i + 1} {opportunity}")
        if opportunity and opportunity.process and opportunity.process.items:
            for j, item in enumerate(opportunity.process.items):
                print(f"  Step {j + 1}: {item}")

    assert opportunities[1]
    assert opportunities[1].process.items[3].type_ == ProcessItemType.TECHNICAL_CODING
    assert opportunities[3]
    assert opportunities[3].process.items[3].type_ == ProcessItemType.TECHNICAL_TAKE_HOME

    with pytest.raises(ValidationError):
        bad_data = ProcessItemCreate(
            process_type=ProcessItemType.UNKNOWN, location_type="inperson", contact_type="unknown"
        ).model_dump()
        ProcessItemCreate.model_validate(bad_data)
